[versions]
accompanist = '0.36.0'
activity-compose = "1.11.0"
agp = "8.13.1"
androidx-test-ext-junit = "1.3.0"
appcompat = "1.6.1"
codeScanner = "16.1.0"
coil = "2.7.0"
compose-bom = "2025.11.00"
compose-compiler = "1.5.14"
compose-foundation = "1.5.5"
compose-material = "1.5.5"
composeNavigation = "2.9.6"
constraintlayout = "2.1.4"
core-ktx = "1.17.0"
coroutines = "1.10.2"
datastore = "1.2.0"
firebaseBom = "34.6.0"
googleServicesPlugin = "4.4.4"
hilt = "2.57.2"
hiltAndroidx = "1.3.0"
junit = "4.13.2"
kotlin = "2.2.21"
kotlinx-serialization = "2.2.21"
kotlinx-serialization-json = "1.9.0"
kspPlugin = "2.3.2"
lifecycle = "2.9.4"
lifecycleRuntimeCompose = "2.9.4"
lottie = "6.6.6"
material = "1.13.0"
material3 = "1.4.0"
navigation = "2.9.6"
protobuf = "4.33.1"
protobufPlugin = "0.9.5"
qrgenerator = "1.0.1"
retrofit = "3.0.0"
retrofit2-serialization-converter = "1.0.0"
screenshot = "0.0.1-alpha01"
splashScreen = "1.2.0"
timber = "5.0.1"

[libraries]
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "compose-foundation" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "compose-material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3"}
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltAndroidx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-material-iconscore = { module = "androidx.compose.material:material-icons-core" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
play-services-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "codeScanner" }
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }
qrgenerator = { group = "com.github.androidmads", name = "QRGenerator", version.ref = "qrgenerator" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2-serialization-converter" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen"}
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

[bundles]
accompianistPager = ["accompanist-pager", "accompanist-pager-indicators"]
coreLibs = ["core-ktx", "hilt"]
dataStoreLibs = ["datastore", "protobuf-kotlin-lite"]
jetpackComposeLibs = ["compose-animation", "compose-foundation", "compose-material", "compose-material3", "compose-navigation", "compose-runtime-livedata", "compose-ui", "compose-ui-tooling-preview", "compose-material-iconscore", "compose-material-iconsext"]
jetpackComposeLibsDebug = ["compose-ui-tooling"]
lifecycleLibs = ["lifecycle-livedata", "lifecycle-runtime", "lifecycle-viewmodel", "lifecycle-viewmodel-compose", "lifecycle-process"]
networkLibs = ["retrofit", "kotlinx-serialization-json", "retrofit-serialization-converter"]
uiLibs = ["material"]

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinx-serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot"}
